### ISSUE TITLE
CPL + BOM Files verfügbar

### ISSUE THREAD

**Issue by NemoN** [der-pw/ESP-12_WLED-Controller#1]
Hallo,

hast du evtl. auch die CPL und BOM Files (Excel Files)?
Dann könnte man die Platine automatisch bestücken lassen.

Grüße
Thomas

**Comment by der-pw** [comment]
Hi,

habe ich nicht erstellt.
Ich habe zum Handlöten alle Teile da.
Aber du kannst dich gern dran auslassen. 😉

Schöne Grüße,
Patrick

**Comment by SoulL3Zz** [comment]
Hi,

ich habe mal die BOM und CPL Files erstellt.
Leider fehlen aktuell noch die Pinheader und der Reset Button.

[ESP-12_WLED-Controller JLCPCB BOM.xlsx](https://github.com/der-pw/ESP-12_WLED-Controller/files/7865564/ESP-12_WLED-Controller.JLCPCB.BOM.xlsx)
[ESP-12_WLED-Controller JLCPCB CPL.xlsx](https://github.com/der-pw/ESP-12_WLED-Controller/files/7865565/ESP-12_WLED-Controller.JLCPCB.CPL.xlsx)

**Comment by der-pw** [comment]
Sehr cool!
Witzigerweise hab ich mir gestern damit auch den Abend vertrödelt.
Die Teilesuche bei JLC ist ja auch nicht gerade mein Freund geworden.
Komplett zerstört hat mich aber die blöde neue Excelversion hier, die einen total blöden CSV-Import hat. 🙄

Für den Taster hatte ich C329185 gefunden.
C4 hatte ich weggelassen. Bestücken die THT?
Die Pinheader könnte man ja auch von Hand löten.

**Comment by SoulL3Zz** [comment]
Ja die Suchfunktion bei JLC ist echt nervig. 🙄 
Bis ich endlich die fertigen Dateien hatte sind auch Stunden vergangen. Teilweise stimmt die Dokumentation von denen auch nicht. Zum Schluss habe ich mir die Sample Files von denen runtergeladen und geschaut wie das ganze aufgebaut sein muss.

Diese Video fand ich ganz hilfreich: [Link](https://youtu.be/VejO8rDdhzo)

Ah danke, dann werde ich den noch ergänzen.
Ja, die bestücken auch THT: [Link](https://jlcpcb.com/smt-assembly)

Die Pinheader habe ich weggelassen, da Kicad nicht genau die richtige Position ausgibt. JLC benötigt immer die mittigen Koordinaten von den Bauteilen. Kicad gibt mir für die Pinheader nur die Eckkoordinaten aus.

**Comment by der-pw** [comment]
Ich habe mal gerechnet. Durch die vielen "extendend" Teile ist das Bestücken schon ein ziemlich teuer Spaß.
Gut, meine ESP12 hab ich nicht so günstig gekauft, wie es JLC anbietet, aber die zusätzlichen Kosten für den Bestücker sind schon happig. Wenn man sich die Teile vorsortiert bekomme ich in ca. 8 Minuten so eine Platine fertig. Gut, das Buffer-Gate hats schon in sich. Also ich werd BOM nicht mehr weiter verfolgen.
Beim nächsten Mal werde ich aber mal eine Schablone mitbestellen.

**Comment by der-pw** [comment]
Hab aus den aktuellen Daten nun doch einmal BOM und CPL generiert. 
https://github.com/der-pw/ESP-12_WLED-Controller/tree/master/Gerber

**Comment by SoulL3Zz** [comment]
Hab gesehen, dass die Position von U1 nicht passt. U1 müsste noch um 180 Grad gedreht werden.
[POS-ESP-12_WLED-Controller.csv](https://github.com/der-pw/ESP-12_WLED-Controller/files/8011088/POS-ESP-12_WLED-Controller.csv)
