### ISSUE TITLE
automatischer Reboot 

### ISSUE THREAD

**Issue by SoulL3Zz** [der-pw/ESP-12_WLED-Controller#2]
Hallo,

ich habe festgestellt, dass wenn ich den Relais-Ausgang Schalte, der ESP-12 sich zurücksetzt und rebootet.

Zunächst habe ich dein Eingang der LED's mit auf dauerhaft +5V gelegt und nicht wie eigentlich vorgesehen auf WS-Strip_VCC.
Das Problem trat seitdem nur noch sporadisch auf.

Zusätzlich habe ich nun den Relais-Ausgang in der Software deaktiviert. Mit dieser Lösung fahre ich bisher ganz gut.
Das Ziel war ja eigentlich, die LED's "komplett" auszuschalten, aber das funktioniert nun nicht mehr.

Daher meine Frage, hatte jemand schon das gleiche Problem?

**Comment by der-pw** [comment]
Hi,

ich kann das Problem nicht nachvollziehen.
Die Geräte, die ich alle gebaut habe, und einige andere, von denen ich weiß, laufen alle problemlos.
Ein vernünftiges Foto vom Aufbau könnte hier hilfreich sein. Welche Version von WLED ist installiert?

**Comment by SoulL3Zz** [comment]
Hi,

ich habe mittlerweile herausgefunden, dass das Problem nur bei kurzen LED Streifen (45 LED's) auftritt.
Bei längeren LED Streifen (90-170 LED's) ist das Problem nicht vorhanden, allerdings resettet sich der ESP nach gewisser Zeit automatisch.

Ich habe bisher sieben Controller zusammengelötet und bei jedem war das gleiche Problem.
Hier ein kleines Video erstellt, wo man erkennen kann, dass der ESP-12 kurz nachdem das Licht ausgeschaltet ist automatisch rebootet: [Link zum Video](https://youtu.be/A6nTGhMkRpw) (ungefähr bei Sekunde 8)

Es macht auch keinen Unterschied, ob ich die LED's über einen Button oder über die Software ausschalte.

Aktuell ist die Version 0.12.0 installiert. Geflasht wurde über den Webinstaller von WLED.
Die verwendeten LED's sind SK6812 RGBW.

**Comment by der-pw** [comment]
Hmm, in der Tat ein sehr merkwürdiges Phänomen.
Ich erkenne einen ESP-12**E**. Könnte das das Problem sein? Ich hatte am Anfang auch E Module und Probleme mit dem Sleep.
Danach habe ich alles F Module verbaut und aus vertrauenswürdiger Quelle. Gib halt reichlich Hinweise auf schlechte, gefälschte Module.
Sag mal, die Flyback-Diode ist aber nicht verkehrt eingelötet? Man sieht es schlecht, aber es hat irgendwie den Anschein auf mich.

**Comment by SoulL3Zz** [comment]
Okay, aktuell habe ich auch den ESP-12E verbaut. Werde die Module mal auf den ESP-12F umbauen.

Die Shottky-Diode müsste eigentlich passen, werde ich aber auch nochmal kontrollieren.

**Comment by der-pw** [comment]
So sieht sie vom Aufbau her ja gut aus, außer dass ich viel geiziger beim Lötzinn bin. 😁
Porbier das mal aus mit dem Modul, ja. Bin mir fast sicher, dass es danach läuft.
Zumindest hast du die letzte Boardrevision, kann also schonmal nicht am fehlenden Gate-R an Q1 liegen. Den hatte ich dummerweise anfangs vergessen, aber selbst damit laufen bei mir noch welche, ohne Probleme.

Könntest allerdings auch mal die letzte 0.13 beta (https://install.wled.me/v2.htm) testen. Zumindest waren die Probleme mit dem Standby an einem Gerät, das noch mit E-Modul rumliegt, weg.

**Comment by SoulL3Zz** [comment]
Danke, hab leider nur noch 1mm Lötzinn, da fällt mir das Dosieren nicht so leicht. 😄 

Ich habe den Gatewiderstand allerdings etwas größer gewählt um den Strom zu begrenzen. Aktuell sind 330 Ohm verbaut.

Auf einem Gerät ist jetzt die letzte Version installiert, das Problem mit dem automatischen reboot bleibt aber weiterhin bestehen.

**Comment by der-pw** [comment]
> Ich habe den Gatewiderstand allerdings etwas größer gewählt  

Danke für den Hinweis, hatte ich lokal sogar schon geändert, aber noch nicht veröffentlicht.

Schauen wir mal, was passiert, wenn du das Modul getauscht hast.

**Comment by SoulL3Zz** [comment]
Ich habe nun den ESP-12E gegen einen ESP12-F getauscht und habe weiterhin das Problem, dass er sich beim ausschalten kurzer LED-Streifen zurücksetzt.
Ich schaue auch mal, ob sich das neue Modul immer noch nach einiger Zeit automatisch zurücksetzt. Sollte er das nicht tun, werde ich meine jetzigen Platinen auf den ESP12-F umrüsten.

**Comment by SoulL3Zz** [comment]
Ich habe in dem WLED Github Repository ein Issue gefunden, welches einen meiner Fehler beschreibt: [Link](https://github.com/Aircoookie/WLED/issues/2017)

Dann bleibt nur noch die Ursache für das Rebooten nach dem Ausschalten herauszufinden.

**Comment by der-pw** [comment]
Könnte das Problem vielleicht auch vom Netzteil ausgelöst werden?
Zeig doch mal bitte ein Foto deines Aufbaus.
Im Video kann man nicht alles erkennen.

**Comment by SoulL3Zz** [comment]
Da ich bereits mehrere Netzteile ausprobiert habe, halte ich das für unwahrscheinlich.

Tatsächlich habe ich aber festgestellt, dass das Problem mit dem zurücksetzen nach dem Ausschalten, durch den ESP-12F und der neusten Version (0.13.0-b6) etwas besser geworden ist.

**Comment by SoulL3Zz** [comment]
![Uploading 412CAC35-07D4-48BF-AC53-9896FA49F01C.jpeg…]()

**Comment by SoulL3Zz** [comment]
Hier ein Bild von meinem Aufbau: [Link](https://ibb.co/6BZW8QC)

**Comment by der-pw** [comment]
> Da ich bereits mehrere Netzteile ausprobiert habe  

Hab ich mir auch schon fast gedacht, wollte aber wenigstens fragen.
Aufbau sieht auch gut aus.

Ich löte morgen mal meine letzte Platine zusammen und werde da mal Tests machen, mit unterschiedlich langen Strips.

**Comment by der-pw** [comment]
Ich habe heute nochmal einen V1.1 Controller zusammengelötet. Ist auch mit einem ESP12-F bestückt.
Daran hängt ein 1m langer Strip, also 60 LEDs. Nach einer guten Stunde hat er sich einmal resettet. Da lief er aber auch noch im AP Modus, weil ich zu faul war, das Ding ins WLAN zu hängen. Danach habe ich ihn als Client ins WLAN geholt und jetzt läuft er seit ca. drei Stunden durch. Ob es damit was zu tun hat, kann ich nicht sagen. Hast du WLAN-sleep mal deaktiviert?

**Comment by SoulL3Zz** [comment]
Okay, WLAN-Sleep habe ich auch deaktiviert. Hast du das mit einer statischen Farbe oder mit einem Effekt ausprobiert. Ich habe den Eindruck, dass der ESP sich bei den Effekten schneller zurücksetzt, als wie wenn nur eine Farbe leuchtet.

**Comment by SoulL3Zz** [comment]
Ich werde jetzt nochmal ein paar Platinen mit dem ESP-12F fertig machen und das ganze weiter beobachten.

**Comment by SoulL3Zz** [comment]
So wie es aussieht laufen die Platinen mit dem ESP-12F wesentlich stabiler.
Dieser läuft jetzt seit über einem Tag ohne Probleme und hat sich nicht automatisch zurückgesetzt.

![image](https://user-images.githubusercontent.com/34695324/149992531-829fd79f-2cc2-44f2-b255-3250d6a77fb9.png)

**Comment by der-pw** [comment]
Hast du ihn mit Effekt durchlaufen lassen oder im Standby?
Meiner hat sich nur kurz nach den Start vorhin einmal resettet und läuft jetzt aber durch.

Ich will am Wochenende mal mit dem Oszi dran.
Vielleicht ribbelt es auch zu heftig hinter dem LDO.
Hast du auch des TS1117 verbaut?

Ich glaube aber nur schwer, dass die Transistrorschaltung dahinter was damit zu tun hat.

**Comment by SoulL3Zz** [comment]
Teils/Teils
In letzter Zeit nutze ich die Effekte weniger.
Aber im Standby läuft er auch durch.

Ja, den nutze ich auch.
Das habe ich auch schon überlegt, hab aber leider nicht die Möglichkeit das zu überprüfen.

**Comment by der-pw** [comment]
Bei dem Effekt tritt es sehr häufig auf. 
`{"on":true,"bri":71,"transition":7,"mainseg":0,"seg":[{"id":0,"start":0,"stop":60,"grp":1,"spc":0,"of":0,"on":true,"bri":255,"cct":127,"col":[[255,0,0],[0,0,0],[0,0,0]],"fx":16,"sx":130,"ix":30,"pal":2,"sel":true,"rev":true,"mi":true},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0}]} `

Ripple war kaum messbar. 38mVpp, die Node-MCU, die ich noch getestet habe, hatte denselben Wert. 
Hab in den letzten Tagen, das Board auf den ESP32 umgebaut. Daten liegen schon bei JLC. Im subchannel auf Reddit findet man auch vermehrt Themen, die solch ähnliche Probleme melden. Die Gründe sind ganz verschiedene. 

Ne Lösung hab ich also auch nicht mehr, außer möglicherweise das Upgrade auf ESP32.

**Comment by SoulL3Zz** [comment]
Okay
Vor einigen Tagen hatte ich hier auch schon ein Issue verlinkt, wo jemand das gleiche Problem hat.

Ich hatte bereits auch schon angefangen die Platine auf den ESP32 umzubauen. 👍 
Ist die Platine bei dir breiter geworden? Da der ESP32 ja etwas länger als der ESP12 ist, habe ich schon überlegt, ob ich eine weitere GND Klemme hinzufüge.

Habe allerdings mit der Bestellung gezögert, da der ESP32 teilweise Probleme mit der WLAN Verbindung haben soll.

**Comment by der-pw** [comment]
Schau mal hier, das ist das Repo https://github.com/der-pw/ESP-32_WLED-Controller
und ein gerendertes Modell der Platine.
Maße sind jetzt 33x63,4mm ist also breiter und auch etwas länger geworden.
Wie du siehst, habe ich aber auch aus dem Fehler mit dem 2. Masseanschluss gelernt. Ich glaube so ist es jetzt besser, da verschmerze ich 2mm mehr Breite. ;-)

Hab jetzt nochmal WLED selbst kompilliert und so alles rausgeworfen was ich nicht brache Blynk, Alexa usw.
Keine Ahnung ob es was bringt. Ich berichte! :-)

**Comment by SoulL3Zz** [comment]
Das sieht doch schonmal vielversprechend aus. 😃 
Alternativ könnte man ja überlegen, ob man die Platine auch über einen DC Power Jack versorgt. Bei kürzeren Streifen sind diese vollkommen ausreichend und man benötigt keinen zusätzlichen Adapter. Vorschlagen würde ich eine Hybrid-Lösung, sodass man sich aussuchen kann, welche Variante man nutzt.

**Comment by der-pw** [comment]
Dankeschön :-)
DC Jack schreibe ich mal auf meine Liste.

**Comment by der-pw** [comment]
Vielleicht noch zu früh zum "feiern" aber ich schreibe es trotzdem mal, weil mich das Thema schon arg beschäftigt.
Zuerst einmal, bin ich sicher, dass einige diese Platine inzwischen nachgebaut haben, und der Fehler eig. schon häufiger hätte bei mir angefragt werden müssen. Irgendwie hats mich jetzt doch gepackt.

Nachdem ich auf meiner Testplatine in den letzten Tagen:
- den Relay-Pin geändert habe (IO13/IO14)
- neben den 100nF noch einen 10µF Kerko vor VCC am ESP gelötet habe
- den Linearregler durch ein komplettes Modul mit AMS1117 getauscht habe
- die Mosfetschaltung komplett totgelegt habe

... habe ich heute mal einen Wemos D1 mini mit zur Arbeit genommen und 8 Stunden problemlos durchlaufen lassen, ohne Reset nix! Nun habe ich das ESP12 Modul vom Wemos runtergelötet und in meine Testplatine eingelötet und anders herum.
Der Wemos mit dem "Absturz-Modul" hat sich nach 23min. resettet. Meine Testplatine mit dem ESP12 aus dem Wemos läuft nun seit über einer Stunde durch.

**Comment by der-pw** [comment]
Rätsel gelöst!
https://github.com/Aircoookie/WLED/wiki/FAQ#why-is-gpio2d4-the-default-led-pin

Keine schöne Sache. Hatte mich ja mal für IO4 entschieden, damit die Datenleitung im ausgeschalteten Zustand nicht permanent unter 5V steht. Das war ne blöde Idee. Dass WLED IO2 nimmt, weil dieser Hardware UART ist und der Bit-Banging Treiber dem gnadenlos unterlegen ist, war mir so nicht klar.

Hab jetzt den Trace auf der Unterseite gekappt und den Eingang am Buffer-Gate auf IO2 gelegt.
Damit die Datenleitung im ausgeschalteten Zustand auch LOW steuere ich  OE vom Buffer-Gate über den Pullup vom P-MOSFET mit.

![image](https://user-images.githubusercontent.com/44023915/151664149-d6ecab77-8357-428b-af2a-843c4da182eb.png)

**Comment by SoulL3Zz** [comment]
Super, Glückwunsch zum gefundenen Fehler 😃 👍 
Darauf muss man ja auch erstmal kommen.

Das werde ich bei meine Platinen auch mal ausprobieren

**Comment by der-pw** [comment]
Ja, war auch nicht so einfach.
Hab die Platine nun aktualisiert und gleich noch ein paar Änderungen vorgenommen.
